version: '3.8'

services:
  auth-service:
    build: ./auth_service
    # ports: # - "8080:8080"
    networks:
      - app-network
  api-gateway:
    image: nginx:latest
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:8081"
    depends_on:
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
