openapi: 3.0.3
info:
  title: Promo Code Proxy API
  description: API Proxy for the Promo Code Service with authentication and authorization.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

paths:
  /promos:
    get:
      summary: Get paginated list of promo codes
      tags:
        - Promo Codes
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      security:
        - jwtAuth: []
        - basicAuth: []
      responses:
        "200":
          description: List of promo codes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Promo'

    post:
      summary: Create a new promo code
      tags:
        - Promo Codes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromoCreate'
      security:
        - jwtAuth: []
        - basicAuth: []
      responses:
        "201":
          description: Promo code created successfully

  /promos/{id}:
    get:
      summary: Get a promo code by ID
      tags:
        - Promo Codes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - jwtAuth: []
        - basicAuth: []
      responses:
        "200":
          description: Promo code details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Promo'
        "404":
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update an existing promo code
      tags:
        - Promo Codes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromoUpdate'
      security:
        - jwtAuth: []
        - basicAuth: []
      responses:
        "200":
          description: Promo code updated successfully
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a promo code
      tags:
        - Promo Codes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - jwtAuth: []
        - basicAuth: []
      responses:
        "204":
          description: Promo code deleted successfully
        "404":
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    jwtAuth:
      type: apiKey
      in: cookie
      name: jwt_token
    basicAuth:
      type: http
      scheme: basic

  responses:
    BadRequest:
      description: Bad request
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: Resource not found

  schemas:
    Promo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        author_id:
          type: string
          format: uuid
        discount_rate:
          type: number
        promo_code:
          type: string
        creation_date:
          type: string
          format: date-time
        update_date:
          type: string
          format: date-time

    PromoCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        author_id:
          type: string
          format: uuid
        discount_rate:
          type: number
        promo_code:
          type: string
      required:
        - title
        - author_id
        - discount_rate
        - promo_code

    PromoUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        discount_rate:
          type: number
      required:
        - title
