// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/stats/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsService_GetPromoStats_FullMethodName    = "/stats.StatsService/GetPromoStats"
	StatsService_GetPromoViews_FullMethodName    = "/stats.StatsService/GetPromoViews"
	StatsService_GetPromoClicks_FullMethodName   = "/stats.StatsService/GetPromoClicks"
	StatsService_GetPromoComments_FullMethodName = "/stats.StatsService/GetPromoComments"
	StatsService_GetTopPromos_FullMethodName     = "/stats.StatsService/GetTopPromos"
	StatsService_GetTopUsers_FullMethodName      = "/stats.StatsService/GetTopUsers"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	GetPromoStats(ctx context.Context, in *PromoRequest, opts ...grpc.CallOption) (*PromoStats, error)
	GetPromoViews(ctx context.Context, in *PromoRequest, opts ...grpc.CallOption) (*DailyStats, error)
	GetPromoClicks(ctx context.Context, in *PromoRequest, opts ...grpc.CallOption) (*DailyStats, error)
	GetPromoComments(ctx context.Context, in *PromoRequest, opts ...grpc.CallOption) (*DailyStats, error)
	GetTopPromos(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopStats, error)
	GetTopUsers(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopStats, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) GetPromoStats(ctx context.Context, in *PromoRequest, opts ...grpc.CallOption) (*PromoStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoStats)
	err := c.cc.Invoke(ctx, StatsService_GetPromoStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetPromoViews(ctx context.Context, in *PromoRequest, opts ...grpc.CallOption) (*DailyStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyStats)
	err := c.cc.Invoke(ctx, StatsService_GetPromoViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetPromoClicks(ctx context.Context, in *PromoRequest, opts ...grpc.CallOption) (*DailyStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyStats)
	err := c.cc.Invoke(ctx, StatsService_GetPromoClicks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetPromoComments(ctx context.Context, in *PromoRequest, opts ...grpc.CallOption) (*DailyStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyStats)
	err := c.cc.Invoke(ctx, StatsService_GetPromoComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetTopPromos(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopStats)
	err := c.cc.Invoke(ctx, StatsService_GetTopPromos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetTopUsers(ctx context.Context, in *TopRequest, opts ...grpc.CallOption) (*TopStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopStats)
	err := c.cc.Invoke(ctx, StatsService_GetTopUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility.
type StatsServiceServer interface {
	GetPromoStats(context.Context, *PromoRequest) (*PromoStats, error)
	GetPromoViews(context.Context, *PromoRequest) (*DailyStats, error)
	GetPromoClicks(context.Context, *PromoRequest) (*DailyStats, error)
	GetPromoComments(context.Context, *PromoRequest) (*DailyStats, error)
	GetTopPromos(context.Context, *TopRequest) (*TopStats, error)
	GetTopUsers(context.Context, *TopRequest) (*TopStats, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServiceServer struct{}

func (UnimplementedStatsServiceServer) GetPromoStats(context.Context, *PromoRequest) (*PromoStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromoStats not implemented")
}
func (UnimplementedStatsServiceServer) GetPromoViews(context.Context, *PromoRequest) (*DailyStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromoViews not implemented")
}
func (UnimplementedStatsServiceServer) GetPromoClicks(context.Context, *PromoRequest) (*DailyStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromoClicks not implemented")
}
func (UnimplementedStatsServiceServer) GetPromoComments(context.Context, *PromoRequest) (*DailyStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromoComments not implemented")
}
func (UnimplementedStatsServiceServer) GetTopPromos(context.Context, *TopRequest) (*TopStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopPromos not implemented")
}
func (UnimplementedStatsServiceServer) GetTopUsers(context.Context, *TopRequest) (*TopStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopUsers not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}
func (UnimplementedStatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_GetPromoStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPromoStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPromoStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPromoStats(ctx, req.(*PromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetPromoViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPromoViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPromoViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPromoViews(ctx, req.(*PromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetPromoClicks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPromoClicks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPromoClicks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPromoClicks(ctx, req.(*PromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetPromoComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetPromoComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetPromoComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetPromoComments(ctx, req.(*PromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetTopPromos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetTopPromos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetTopPromos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetTopPromos(ctx, req.(*TopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetTopUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetTopUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetTopUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetTopUsers(ctx, req.(*TopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPromoStats",
			Handler:    _StatsService_GetPromoStats_Handler,
		},
		{
			MethodName: "GetPromoViews",
			Handler:    _StatsService_GetPromoViews_Handler,
		},
		{
			MethodName: "GetPromoClicks",
			Handler:    _StatsService_GetPromoClicks_Handler,
		},
		{
			MethodName: "GetPromoComments",
			Handler:    _StatsService_GetPromoComments_Handler,
		},
		{
			MethodName: "GetTopPromos",
			Handler:    _StatsService_GetTopPromos_Handler,
		},
		{
			MethodName: "GetTopUsers",
			Handler:    _StatsService_GetTopUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stats/stats.proto",
}
