// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/stats/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromoId       string                 `protobuf:"bytes,1,opt,name=promo_id,json=promoId,proto3" json:"promo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoRequest) Reset() {
	*x = PromoRequest{}
	mi := &file_proto_stats_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoRequest) ProtoMessage() {}

func (x *PromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoRequest.ProtoReflect.Descriptor instead.
func (*PromoRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *PromoRequest) GetPromoId() string {
	if x != nil {
		return x.PromoId
	}
	return ""
}

type TopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"` // "view", "click", "comment"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopRequest) Reset() {
	*x = TopRequest{}
	mi := &file_proto_stats_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopRequest) ProtoMessage() {}

func (x *TopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopRequest.ProtoReflect.Descriptor instead.
func (*TopRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *TopRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

type PromoStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         int32                  `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	Clicks        int32                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Comments      int32                  `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoStats) Reset() {
	*x = PromoStats{}
	mi := &file_proto_stats_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoStats) ProtoMessage() {}

func (x *PromoStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoStats.ProtoReflect.Descriptor instead.
func (*PromoStats) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *PromoStats) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *PromoStats) GetClicks() int32 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *PromoStats) GetComments() int32 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type DailyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyData) Reset() {
	*x = DailyData{}
	mi := &file_proto_stats_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyData) ProtoMessage() {}

func (x *DailyData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyData.ProtoReflect.Descriptor instead.
func (*DailyData) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{3}
}

func (x *DailyData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyData) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DailyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*DailyData           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStats) Reset() {
	*x = DailyStats{}
	mi := &file_proto_stats_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStats) ProtoMessage() {}

func (x *DailyStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStats.ProtoReflect.Descriptor instead.
func (*DailyStats) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{4}
}

func (x *DailyStats) GetStats() []*DailyData {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TopEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopEntry) Reset() {
	*x = TopEntry{}
	mi := &file_proto_stats_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopEntry) ProtoMessage() {}

func (x *TopEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopEntry.ProtoReflect.Descriptor instead.
func (*TopEntry) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{5}
}

func (x *TopEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopEntry) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TopEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopStats) Reset() {
	*x = TopStats{}
	mi := &file_proto_stats_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopStats) ProtoMessage() {}

func (x *TopStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopStats.ProtoReflect.Descriptor instead.
func (*TopStats) Descriptor() ([]byte, []int) {
	return file_proto_stats_stats_proto_rawDescGZIP(), []int{6}
}

func (x *TopStats) GetEntries() []*TopEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_stats_stats_proto protoreflect.FileDescriptor

const file_proto_stats_stats_proto_rawDesc = "" +
	"\n" +
	"\x17proto/stats/stats.proto\x12\x05stats\")\n" +
	"\fPromoRequest\x12\x19\n" +
	"\bpromo_id\x18\x01 \x01(\tR\apromoId\"$\n" +
	"\n" +
	"TopRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\"V\n" +
	"\n" +
	"PromoStats\x12\x14\n" +
	"\x05views\x18\x01 \x01(\x05R\x05views\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x05R\x06clicks\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\x05R\bcomments\"5\n" +
	"\tDailyData\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"4\n" +
	"\n" +
	"DailyStats\x12&\n" +
	"\x05stats\x18\x01 \x03(\v2\x10.stats.DailyDataR\x05stats\"0\n" +
	"\bTopEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"5\n" +
	"\bTopStats\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.stats.TopEntryR\aentries2\xdd\x02\n" +
	"\fStatsService\x127\n" +
	"\rGetPromoStats\x12\x13.stats.PromoRequest\x1a\x11.stats.PromoStats\x127\n" +
	"\rGetPromoViews\x12\x13.stats.PromoRequest\x1a\x11.stats.DailyStats\x128\n" +
	"\x0eGetPromoClicks\x12\x13.stats.PromoRequest\x1a\x11.stats.DailyStats\x12:\n" +
	"\x10GetPromoComments\x12\x13.stats.PromoRequest\x1a\x11.stats.DailyStats\x122\n" +
	"\fGetTopPromos\x12\x11.stats.TopRequest\x1a\x0f.stats.TopStats\x121\n" +
	"\vGetTopUsers\x12\x11.stats.TopRequest\x1a\x0f.stats.TopStatsB+Z)/home/user/loyalty-program-platform/statsb\x06proto3"

var (
	file_proto_stats_stats_proto_rawDescOnce sync.Once
	file_proto_stats_stats_proto_rawDescData []byte
)

func file_proto_stats_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stats_stats_proto_rawDesc), len(file_proto_stats_stats_proto_rawDesc)))
	})
	return file_proto_stats_stats_proto_rawDescData
}

var file_proto_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_stats_stats_proto_goTypes = []any{
	(*PromoRequest)(nil), // 0: stats.PromoRequest
	(*TopRequest)(nil),   // 1: stats.TopRequest
	(*PromoStats)(nil),   // 2: stats.PromoStats
	(*DailyData)(nil),    // 3: stats.DailyData
	(*DailyStats)(nil),   // 4: stats.DailyStats
	(*TopEntry)(nil),     // 5: stats.TopEntry
	(*TopStats)(nil),     // 6: stats.TopStats
}
var file_proto_stats_stats_proto_depIdxs = []int32{
	3, // 0: stats.DailyStats.stats:type_name -> stats.DailyData
	5, // 1: stats.TopStats.entries:type_name -> stats.TopEntry
	0, // 2: stats.StatsService.GetPromoStats:input_type -> stats.PromoRequest
	0, // 3: stats.StatsService.GetPromoViews:input_type -> stats.PromoRequest
	0, // 4: stats.StatsService.GetPromoClicks:input_type -> stats.PromoRequest
	0, // 5: stats.StatsService.GetPromoComments:input_type -> stats.PromoRequest
	1, // 6: stats.StatsService.GetTopPromos:input_type -> stats.TopRequest
	1, // 7: stats.StatsService.GetTopUsers:input_type -> stats.TopRequest
	2, // 8: stats.StatsService.GetPromoStats:output_type -> stats.PromoStats
	4, // 9: stats.StatsService.GetPromoViews:output_type -> stats.DailyStats
	4, // 10: stats.StatsService.GetPromoClicks:output_type -> stats.DailyStats
	4, // 11: stats.StatsService.GetPromoComments:output_type -> stats.DailyStats
	6, // 12: stats.StatsService.GetTopPromos:output_type -> stats.TopStats
	6, // 13: stats.StatsService.GetTopUsers:output_type -> stats.TopStats
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_stats_stats_proto_init() }
func file_proto_stats_stats_proto_init() {
	if File_proto_stats_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stats_stats_proto_rawDesc), len(file_proto_stats_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_stats_proto = out.File
	file_proto_stats_stats_proto_goTypes = nil
	file_proto_stats_stats_proto_depIdxs = nil
}
