// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/promo.proto

package loyalty_service

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Promo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	DiscountRate  float64                `protobuf:"fixed64,5,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	PromoCode     string                 `protobuf:"bytes,6,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	CreationDate  *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	UpdateDate    *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=update_date,json=updateDate,proto3" json:"update_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promo) Reset() {
	*x = Promo{}
	mi := &file_proto_promo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promo) ProtoMessage() {}

func (x *Promo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promo.ProtoReflect.Descriptor instead.
func (*Promo) Descriptor() ([]byte, []int) {
	return file_proto_promo_proto_rawDescGZIP(), []int{0}
}

func (x *Promo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Promo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Promo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Promo) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Promo) GetDiscountRate() float64 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *Promo) GetPromoCode() string {
	if x != nil {
		return x.PromoCode
	}
	return ""
}

func (x *Promo) GetCreationDate() *timestamp.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Promo) GetUpdateDate() *timestamp.Timestamp {
	if x != nil {
		return x.UpdateDate
	}
	return nil
}

type CreatePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	DiscountRate  float64                `protobuf:"fixed64,4,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	PromoCode     string                 `protobuf:"bytes,5,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePromoRequest) Reset() {
	*x = CreatePromoRequest{}
	mi := &file_proto_promo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePromoRequest) ProtoMessage() {}

func (x *CreatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePromoRequest.ProtoReflect.Descriptor instead.
func (*CreatePromoRequest) Descriptor() ([]byte, []int) {
	return file_proto_promo_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePromoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePromoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePromoRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreatePromoRequest) GetDiscountRate() float64 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *CreatePromoRequest) GetPromoCode() string {
	if x != nil {
		return x.PromoCode
	}
	return ""
}

type GetPromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPromoRequest) Reset() {
	*x = GetPromoRequest{}
	mi := &file_proto_promo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoRequest) ProtoMessage() {}

func (x *GetPromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoRequest.ProtoReflect.Descriptor instead.
func (*GetPromoRequest) Descriptor() ([]byte, []int) {
	return file_proto_promo_proto_rawDescGZIP(), []int{2}
}

func (x *GetPromoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdatePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DiscountRate  float64                `protobuf:"fixed64,4,opt,name=discount_rate,json=discountRate,proto3" json:"discount_rate,omitempty"`
	AuthorId      string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PromoCode     string                 `protobuf:"bytes,6,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePromoRequest) Reset() {
	*x = UpdatePromoRequest{}
	mi := &file_proto_promo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePromoRequest) ProtoMessage() {}

func (x *UpdatePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePromoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePromoRequest) Descriptor() ([]byte, []int) {
	return file_proto_promo_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePromoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePromoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePromoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePromoRequest) GetDiscountRate() float64 {
	if x != nil {
		return x.DiscountRate
	}
	return 0
}

func (x *UpdatePromoRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *UpdatePromoRequest) GetPromoCode() string {
	if x != nil {
		return x.PromoCode
	}
	return ""
}

type DeletePromoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePromoRequest) Reset() {
	*x = DeletePromoRequest{}
	mi := &file_proto_promo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePromoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoRequest) ProtoMessage() {}

func (x *DeletePromoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoRequest.ProtoReflect.Descriptor instead.
func (*DeletePromoRequest) Descriptor() ([]byte, []int) {
	return file_proto_promo_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePromoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeletePromoRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type ListPromosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromosRequest) Reset() {
	*x = ListPromosRequest{}
	mi := &file_proto_promo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromosRequest) ProtoMessage() {}

func (x *ListPromosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromosRequest.ProtoReflect.Descriptor instead.
func (*ListPromosRequest) Descriptor() ([]byte, []int) {
	return file_proto_promo_proto_rawDescGZIP(), []int{5}
}

func (x *ListPromosRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPromosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPromosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Promos        []*Promo               `protobuf:"bytes,1,rep,name=promos,proto3" json:"promos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPromosResponse) Reset() {
	*x = ListPromosResponse{}
	mi := &file_proto_promo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPromosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPromosResponse) ProtoMessage() {}

func (x *ListPromosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPromosResponse.ProtoReflect.Descriptor instead.
func (*ListPromosResponse) Descriptor() ([]byte, []int) {
	return file_proto_promo_proto_rawDescGZIP(), []int{6}
}

func (x *ListPromosResponse) GetPromos() []*Promo {
	if x != nil {
		return x.Promos
	}
	return nil
}

var File_proto_promo_proto protoreflect.FileDescriptor

const file_proto_promo_proto_rawDesc = "" +
	"\n" +
	"\x11proto/promo.proto\x12\x05promo\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x02\n" +
	"\x05Promo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12#\n" +
	"\rdiscount_rate\x18\x05 \x01(\x01R\fdiscountRate\x12\x1d\n" +
	"\n" +
	"promo_code\x18\x06 \x01(\tR\tpromoCode\x12?\n" +
	"\rcreation_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\x12;\n" +
	"\vupdate_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateDate\"\xad\x01\n" +
	"\x12CreatePromoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12#\n" +
	"\rdiscount_rate\x18\x04 \x01(\x01R\fdiscountRate\x12\x1d\n" +
	"\n" +
	"promo_code\x18\x05 \x01(\tR\tpromoCode\"!\n" +
	"\x0fGetPromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbd\x01\n" +
	"\x12UpdatePromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rdiscount_rate\x18\x04 \x01(\x01R\fdiscountRate\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12\x1d\n" +
	"\n" +
	"promo_code\x18\x06 \x01(\tR\tpromoCode\"A\n" +
	"\x12DeletePromoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\"=\n" +
	"\x11ListPromosRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\":\n" +
	"\x12ListPromosResponse\x12$\n" +
	"\x06promos\x18\x01 \x03(\v2\f.promo.PromoR\x06promos2\xbf\x02\n" +
	"\fPromoService\x128\n" +
	"\vCreatePromo\x12\x19.promo.CreatePromoRequest\x1a\f.promo.Promo\"\x00\x122\n" +
	"\bGetPromo\x12\x16.promo.GetPromoRequest\x1a\f.promo.Promo\"\x00\x128\n" +
	"\vUpdatePromo\x12\x19.promo.UpdatePromoRequest\x1a\f.promo.Promo\"\x00\x12B\n" +
	"\vDeletePromo\x12\x19.promo.DeletePromoRequest\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\n" +
	"ListPromos\x12\x18.promo.ListPromosRequest\x1a\x19.promo.ListPromosResponse\"\x00B5Z3/home/user/loyalty-program-platform/loyalty_serviceb\x06proto3"

var (
	file_proto_promo_proto_rawDescOnce sync.Once
	file_proto_promo_proto_rawDescData []byte
)

func file_proto_promo_proto_rawDescGZIP() []byte {
	file_proto_promo_proto_rawDescOnce.Do(func() {
		file_proto_promo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_promo_proto_rawDesc), len(file_proto_promo_proto_rawDesc)))
	})
	return file_proto_promo_proto_rawDescData
}

var file_proto_promo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_promo_proto_goTypes = []any{
	(*Promo)(nil),               // 0: promo.Promo
	(*CreatePromoRequest)(nil),  // 1: promo.CreatePromoRequest
	(*GetPromoRequest)(nil),     // 2: promo.GetPromoRequest
	(*UpdatePromoRequest)(nil),  // 3: promo.UpdatePromoRequest
	(*DeletePromoRequest)(nil),  // 4: promo.DeletePromoRequest
	(*ListPromosRequest)(nil),   // 5: promo.ListPromosRequest
	(*ListPromosResponse)(nil),  // 6: promo.ListPromosResponse
	(*timestamp.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*empty.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_proto_promo_proto_depIdxs = []int32{
	7, // 0: promo.Promo.creation_date:type_name -> google.protobuf.Timestamp
	7, // 1: promo.Promo.update_date:type_name -> google.protobuf.Timestamp
	0, // 2: promo.ListPromosResponse.promos:type_name -> promo.Promo
	1, // 3: promo.PromoService.CreatePromo:input_type -> promo.CreatePromoRequest
	2, // 4: promo.PromoService.GetPromo:input_type -> promo.GetPromoRequest
	3, // 5: promo.PromoService.UpdatePromo:input_type -> promo.UpdatePromoRequest
	4, // 6: promo.PromoService.DeletePromo:input_type -> promo.DeletePromoRequest
	5, // 7: promo.PromoService.ListPromos:input_type -> promo.ListPromosRequest
	0, // 8: promo.PromoService.CreatePromo:output_type -> promo.Promo
	0, // 9: promo.PromoService.GetPromo:output_type -> promo.Promo
	0, // 10: promo.PromoService.UpdatePromo:output_type -> promo.Promo
	8, // 11: promo.PromoService.DeletePromo:output_type -> google.protobuf.Empty
	6, // 12: promo.PromoService.ListPromos:output_type -> promo.ListPromosResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_promo_proto_init() }
func file_proto_promo_proto_init() {
	if File_proto_promo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_promo_proto_rawDesc), len(file_proto_promo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_promo_proto_goTypes,
		DependencyIndexes: file_proto_promo_proto_depIdxs,
		MessageInfos:      file_proto_promo_proto_msgTypes,
	}.Build()
	File_proto_promo_proto = out.File
	file_proto_promo_proto_goTypes = nil
	file_proto_promo_proto_depIdxs = nil
}
