// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: promo.proto

package loyalty_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromoService_CreatePromo_FullMethodName  = "/promo.PromoService/CreatePromo"
	PromoService_GetPromo_FullMethodName     = "/promo.PromoService/GetPromo"
	PromoService_UpdatePromo_FullMethodName  = "/promo.PromoService/UpdatePromo"
	PromoService_DeletePromo_FullMethodName  = "/promo.PromoService/DeletePromo"
	PromoService_ListPromos_FullMethodName   = "/promo.PromoService/ListPromos"
	PromoService_AddComment_FullMethodName   = "/promo.PromoService/AddComment"
	PromoService_GetComment_FullMethodName   = "/promo.PromoService/GetComment"
	PromoService_ListComments_FullMethodName = "/promo.PromoService/ListComments"
)

// PromoServiceClient is the client API for PromoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromoServiceClient interface {
	CreatePromo(ctx context.Context, in *CreatePromoRequest, opts ...grpc.CallOption) (*Promo, error)
	GetPromo(ctx context.Context, in *GetPromoRequest, opts ...grpc.CallOption) (*Promo, error)
	UpdatePromo(ctx context.Context, in *UpdatePromoRequest, opts ...grpc.CallOption) (*Promo, error)
	DeletePromo(ctx context.Context, in *DeletePromoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListPromos(ctx context.Context, in *ListPromosRequest, opts ...grpc.CallOption) (*ListPromosResponse, error)
	AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
}

type promoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromoServiceClient(cc grpc.ClientConnInterface) PromoServiceClient {
	return &promoServiceClient{cc}
}

func (c *promoServiceClient) CreatePromo(ctx context.Context, in *CreatePromoRequest, opts ...grpc.CallOption) (*Promo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Promo)
	err := c.cc.Invoke(ctx, PromoService_CreatePromo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promoServiceClient) GetPromo(ctx context.Context, in *GetPromoRequest, opts ...grpc.CallOption) (*Promo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Promo)
	err := c.cc.Invoke(ctx, PromoService_GetPromo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promoServiceClient) UpdatePromo(ctx context.Context, in *UpdatePromoRequest, opts ...grpc.CallOption) (*Promo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Promo)
	err := c.cc.Invoke(ctx, PromoService_UpdatePromo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promoServiceClient) DeletePromo(ctx context.Context, in *DeletePromoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, PromoService_DeletePromo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promoServiceClient) ListPromos(ctx context.Context, in *ListPromosRequest, opts ...grpc.CallOption) (*ListPromosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPromosResponse)
	err := c.cc.Invoke(ctx, PromoService_ListPromos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promoServiceClient) AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, PromoService_AddComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promoServiceClient) GetComment(ctx context.Context, in *GetCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment)
	err := c.cc.Invoke(ctx, PromoService_GetComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promoServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, PromoService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromoServiceServer is the server API for PromoService service.
// All implementations must embed UnimplementedPromoServiceServer
// for forward compatibility.
type PromoServiceServer interface {
	CreatePromo(context.Context, *CreatePromoRequest) (*Promo, error)
	GetPromo(context.Context, *GetPromoRequest) (*Promo, error)
	UpdatePromo(context.Context, *UpdatePromoRequest) (*Promo, error)
	DeletePromo(context.Context, *DeletePromoRequest) (*empty.Empty, error)
	ListPromos(context.Context, *ListPromosRequest) (*ListPromosResponse, error)
	AddComment(context.Context, *AddCommentRequest) (*Comment, error)
	GetComment(context.Context, *GetCommentRequest) (*Comment, error)
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	mustEmbedUnimplementedPromoServiceServer()
}

// UnimplementedPromoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromoServiceServer struct{}

func (UnimplementedPromoServiceServer) CreatePromo(context.Context, *CreatePromoRequest) (*Promo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePromo not implemented")
}
func (UnimplementedPromoServiceServer) GetPromo(context.Context, *GetPromoRequest) (*Promo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromo not implemented")
}
func (UnimplementedPromoServiceServer) UpdatePromo(context.Context, *UpdatePromoRequest) (*Promo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePromo not implemented")
}
func (UnimplementedPromoServiceServer) DeletePromo(context.Context, *DeletePromoRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePromo not implemented")
}
func (UnimplementedPromoServiceServer) ListPromos(context.Context, *ListPromosRequest) (*ListPromosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPromos not implemented")
}
func (UnimplementedPromoServiceServer) AddComment(context.Context, *AddCommentRequest) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedPromoServiceServer) GetComment(context.Context, *GetCommentRequest) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComment not implemented")
}
func (UnimplementedPromoServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedPromoServiceServer) mustEmbedUnimplementedPromoServiceServer() {}
func (UnimplementedPromoServiceServer) testEmbeddedByValue()                      {}

// UnsafePromoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromoServiceServer will
// result in compilation errors.
type UnsafePromoServiceServer interface {
	mustEmbedUnimplementedPromoServiceServer()
}

func RegisterPromoServiceServer(s grpc.ServiceRegistrar, srv PromoServiceServer) {
	// If the following call pancis, it indicates UnimplementedPromoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromoService_ServiceDesc, srv)
}

func _PromoService_CreatePromo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).CreatePromo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoService_CreatePromo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).CreatePromo(ctx, req.(*CreatePromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromoService_GetPromo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).GetPromo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoService_GetPromo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).GetPromo(ctx, req.(*GetPromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromoService_UpdatePromo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).UpdatePromo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoService_UpdatePromo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).UpdatePromo(ctx, req.(*UpdatePromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromoService_DeletePromo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePromoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).DeletePromo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoService_DeletePromo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).DeletePromo(ctx, req.(*DeletePromoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromoService_ListPromos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPromosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).ListPromos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoService_ListPromos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).ListPromos(ctx, req.(*ListPromosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromoService_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoService_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).AddComment(ctx, req.(*AddCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromoService_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoService_GetComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).GetComment(ctx, req.(*GetCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromoService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromoServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromoService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromoServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromoService_ServiceDesc is the grpc.ServiceDesc for PromoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promo.PromoService",
	HandlerType: (*PromoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePromo",
			Handler:    _PromoService_CreatePromo_Handler,
		},
		{
			MethodName: "GetPromo",
			Handler:    _PromoService_GetPromo_Handler,
		},
		{
			MethodName: "UpdatePromo",
			Handler:    _PromoService_UpdatePromo_Handler,
		},
		{
			MethodName: "DeletePromo",
			Handler:    _PromoService_DeletePromo_Handler,
		},
		{
			MethodName: "ListPromos",
			Handler:    _PromoService_ListPromos_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _PromoService_AddComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _PromoService_GetComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _PromoService_ListComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promo.proto",
}
